version: '4.24'


services:

  mongo-db:
    image: mongo:6.0.6
    # restart: always -> cuando el docker desktop se levante, inmediatamente se va a levantar la imagen de mongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    # volumes -> indico que me guarde la data que maneje en un file con ese path. Asi cuando baje docker y vuelva a subirlo la data persiste.
    volumes:
      - ./mongo-test:/data/db
    # ports: - 27018:27017 -> mapeamos el puerto de mi pc (2018 porque puede ser que este siendo usado el 2017 por el mongodb que tengo instalado en mi pc) con el del contenedor 2017
    ports:
      - 27018:27017

  postgres-db:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-test:/var/lib/postgresql/data 
    ports:
      - 5432:5432